/**
 * Utilities for building watermark text and generating a repeating
 * canvas pattern that can be used as a Three.js texture or a CSS
 * background for the DOM overlay.
 */

// ---------------------------------------------------------------------------
// Text Builder
// ---------------------------------------------------------------------------

/**
 * Build the default watermark string for a model.
 */
export function generateWatermarkText(modelName: string): string {
    const date = new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "short",
        day: "numeric",
    });
    return `ARCHION VIEWER · ${modelName.toUpperCase()} · CONFIDENTIAL · ${date}`;
}

// ---------------------------------------------------------------------------
// Canvas Pattern Generator
// ---------------------------------------------------------------------------

export interface WatermarkPatternOptions {
    text: string;
    /** Opacity 0-1. Default 0.12 */
    opacity?: number;
    /** Font size in px. Default 14 */
    fontSize?: number;
    /** Rotation angle in degrees (counter-clockwise). Default -35 */
    angle?: number;
    /** Color of the text. Default "#ffffff" */
    color?: string;
    /** Gap between repetitions in px. Default 80 */
    gap?: number;
}

/**
 * Creates a repeating watermark `<canvas>` pattern and returns its data URL.
 * This can be used as:
 *   - CSS `background-image: url(dataUrl)` on the DOM overlay
 *   - A Three.js `CanvasTexture` on a plane over the model
 */
export function generateWatermarkPatternDataUrl(opts: WatermarkPatternOptions): string {
    const {
        text,
        opacity = 0.12,
        fontSize = 14,
        angle = -35,
        color = "#ffffff",
        gap = 80,
    } = opts;

    // Create an off-screen canvas for a single tile
    const tileCanvas = document.createElement("canvas");
    const rad = (angle * Math.PI) / 180;

    // Measure text width
    const measCtx = tileCanvas.getContext("2d")!;
    measCtx.font = `600 ${fontSize}px "Inter", sans-serif`;
    const textWidth = measCtx.measureText(text).width;

    const tileW = textWidth + gap * 2;
    const tileH = fontSize + gap * 1.5;

    tileCanvas.width = tileW;
    tileCanvas.height = tileH;

    const ctx = tileCanvas.getContext("2d")!;
    ctx.clearRect(0, 0, tileW, tileH);

    ctx.save();
    ctx.globalAlpha = opacity;
    ctx.translate(tileW / 2, tileH / 2);
    ctx.rotate(rad);
    ctx.fillStyle = color;
    ctx.font = `600 ${fontSize}px "Inter", sans-serif`;
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.letterSpacing = "2px";
    ctx.fillText(text, 0, 0);
    ctx.restore();

    return tileCanvas.toDataURL("image/png");
}

/**
 * Returns an inline CSS `background` property string for the DOM overlay.
 */
export function getWatermarkCssBackground(opts: WatermarkPatternOptions): string {
    // We return just the CSS string — the DataURL is generated by the component itself
    // because document is only available in the browser. The component calls
    // generateWatermarkPatternDataUrl() on the client side.
    return `repeating linear-gradient(...)`;
}
