import React from "react";
import Link from "next/link";
import { ArrowLeft } from "@phosphor-icons/react/dist/ssr";
import SmoothScroller from "@/components/SmoothScroller";

export const metadata = {
  title: "Terms and Conditions | ArchionLabs",
  description: "Terms and Conditions for ArchionLabs platforms.",
};

export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-[#111111] text-white selection:bg-white/20 selection:text-white">
      <SmoothScroller />
      <div className="absolute top-0 right-0 w-[800px] h-[800px] bg-white/5 rounded-full blur-[120px] -mr-[400px] -mt-[400px] pointer-events-none"></div>
      
      <div className="max-w-4xl mx-auto px-6 py-24 md:py-32 relative z-10">
        <Link href="/" className="inline-flex items-center gap-2 text-gray-400 hover:text-white transition-colors mb-12 text-sm font-medium">
          <ArrowLeft weight="bold" />
          Back to Home
        </Link>
        
        <div className="space-y-12">
          <header>
            <h1 className="text-4xl md:text-6xl font-medium tracking-tight mb-4">Terms and Conditions</h1>
            <p className="text-gray-400 text-lg">Last updated: March 2026</p>
          </header>

          <div className="space-y-8 text-gray-300 leading-relaxed font-light text-lg">
            <section className="space-y-4">
              <h2 className="text-2xl text-white font-medium">1. Agreement to Terms</h2>
              <p>
                By accessing our website and using the platforms developed by ArchionLabs (including Archion Build, Archion Sim, and Viewer & Share), you agree to be bound by these Terms and Conditions and our Privacy Policy. If you do not agree to these Terms and Conditions, you may not use our platforms.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl text-white font-medium">2. Intellectual Property Rights</h2>
              <p>
                Other than the content you own, under these Terms, ArchionLabs and/or its licensors own all the intellectual property rights and materials contained in our platforms. You are granted a limited license only for purposes of viewing the material contained on this Website and utilizing the platforms as intended.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl text-white font-medium">3. User Obligations</h2>
              <p>
                As a user of our platforms, you agree not to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-gray-400">
                <li>Publish any platform material in any other media without proper authorization.</li>
                <li>Sell, sublicense, and/or otherwise commercialize any platform material.</li>
                <li>Use our platforms in any way that is or may be damaging to the platforms.</li>
                <li>Use our platforms in any way that impacts user access to these platforms.</li>
                <li>Engage in any data mining, data harvesting, data extracting, or any other similar activity in relation to our platforms.</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl text-white font-medium">4. Generated AI Content</h2>
              <p>
                Any floorplans, spatial designs, or architectural simulations generated by ArchionLabs' AI models based on user input belong to the user. ArchionLabs retains the right to use aggregated, anonymized data to improve its machine learning models, except where specifically excluded by an enterprise agreement.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl text-white font-medium">5. Limitation of Liability</h2>
              <p>
                In no event shall ArchionLabs, nor any of its officers, directors, and employees, be held liable for anything arising out of or in any way connected with your use of our platforms, whether such liability is under contract. ArchionLabs, including its officers, directors, and employees shall not be held liable for any indirect, consequential, or special liability arising out of or in any way related to your use of this Website.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl text-white font-medium">6. Governing Law & Jurisdiction</h2>
              <p>
                These Terms will be governed by and interpreted in accordance with the laws of Sri Lanka, and you submit to the non-exclusive jurisdiction of the state and federal courts located in Sri Lanka for the resolution of any disputes.
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
